# Generated by Django 3.2.3 on 2021-05-28 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_room_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='hotel',
        ),
    ]
